Comment out AP2 installation command in requirements.txt
pip install -r requirements.txt
ERROR: Invalid requirement: 'Install with: pip install git+https://github.com/google-agentic-commerce/AP2.git@main' (from line 8 of requirements.txt)
Hint: It looks like a path. File 'Install with: pip install git+https://github.com/google-agentic-commerce/AP2.git@main' does not exist.